### ISSUE TITLE
Error on Docker Desktop with Apple M1 chip

### ISSUE THREAD

**Issue by gayatri-sa** [strapdata/docker-elassandra#21]
I get this error when I try to create a container. I tried explicitly specifying a platform too. Didn't work. Is there any way to get this to work on Apple M1 chip?

```docker run --name my-elassandra strapdata/elassandra:6.2
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x4cb21f, 0x9)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.newosproc(0xc42002a000, 0xc420039fc0)
	/usr/local/go/src/runtime/os_linux.go:160 +0x194
runtime.newm(0x4d6db8, 0x0)
	/usr/local/go/src/runtime/proc.go:1572 +0x132
runtime.main.func1()
	/usr/local/go/src/runtime/proc.go:126 +0x36
runtime.systemstack(0x53ae00)
	/usr/local/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1079

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420024768 sp=0xc420024760
runtime.main()
	/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200247c0 sp=0xc420024768
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200247c8 sp=0xc4200247c0```

**Comment by thaihien93** [comment]
same issue.

**Comment by jrvldam** [comment]
Same for Apple M2

```shell
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc
verso-dev-infra-deps-elassandra-server-1  |
runtime stack:
runtime.throw(0x4cb21f, 0x9)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.newosproc(0xc42002e000, 0xc42003dfc0)
	/usr/local/go/src/runtime/os_linux.go:160 +0x194
runtime.newm(0x4d6db8, 0x0)
	/usr/local/go/src/runtime/proc.go:1572 +0x132
runtime.main.func1()
	/usr/local/go/src/runtime/proc.go:126 +0x36
runtime.systemstack(0x53ae00)
	/usr/local/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1079
verso-dev-infra-deps-elassandra-server-1  |
goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420028768 sp=0xc420028760
runtime.main()
	/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200287c0 sp=0xc420028768
runtime.goexit()
```

It would be lovely to have a way to make it work for mac.

**Comment by nevasik** [comment]
Tell me who solved this problem?
